version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade awscli  # Ensure AWS CLI is up to date
  build:
    commands:
      - echo Packaging Lambda functions...
      - cd index-photos
      - zip -r ../index-photos.zip .  # Create a ZIP file for LF1
      - cd ../search-photos
      - zip -r ../search-photos.zip .  # Create a ZIP file for LF2
  post_build:
    commands:
      - echo Build completed!

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
    - cloudformation-template.yml  # Include CloudFormation template
  discard-paths: yes
