AWSTemplateFormatVersion: '2010-09-09'
Description: Frontend Infrastructure Stack for Photo Manager Application

Parameters:
  LambdaDeploymentBucket:
    Type: String
    Description: The S3 bucket to store Lambda deployment packages

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub "photo-manager-frontend-${AWS::AccountId}"
      
  FrontendBucketOAI:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      Name: "photo-manager-frontend-OAC"
      Description: "OAC for frontend bucket to securely serve content"
      SigningBehavior: "SIGN"
      OriginType: "S3"
  
  FrontendCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CallerReference: !Sub "unique-id-${AWS::AccountId}"
        Comment: "CloudFront Distribution for Frontend"
        Enabled: true
        DefaultRootObject: "index.html"
        Origins:
          - DomainName: !GetAtt FrontendBucket.DomainName
            Id: "FrontendS3Origin"
            S3OriginConfig:
              OriginAccessIdentity: !Sub "arn:aws:cloudfront::${AWS::AccountId}:origin-access-control/E34N6YJSQ1Q5T"
        DefaultCacheBehavior:
          TargetOriginId: "FrontendS3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods:
            - "GET"
            - "HEAD"
          CachedMethods:
            - "GET"
            - "HEAD"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  CloudFrontURL:
    Description: "URL for the CloudFront Distribution"
    Value: !Sub "https://d2zocwrbptli1e.cloudfront.net"
  
  BucketName:
    Description: "Name of the S3 bucket for the frontend"
    Value: !Ref FrontendBucket
