AWSTemplateFormatVersion: '2010-09-09'
Resources:
  IndexPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: index-photos
      Handler: LF1-IndexPhotos.lambda_handler
      Role: arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: index-photos.zip
      Runtime: python3.8
      MemorySize: 128
      Timeout: 60

  SearchPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-photos
      Handler: LF2-SearchPhotos.lambda_handler
      Role: arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: search-photos.zip
      Runtime: python3.8
      MemorySize: 128
      Timeout: 60

  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: photo-manager-backend-bucket

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                  - s3:*
                  - rekognition:*
                Resource: "*"
