Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  IndexPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: IndexPhotosLambda
      Handler: index-photos.LF1-IndexPhotos
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs16.x
      Code:
        S3Bucket: devak-lambda-deployment-buckets # Ensure this is the correct bucket name
        S3Key: index-photos.zip

  SearchPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SearchPhotosLambda
      Handler: search-photos.LF2-SearchPhotos
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs16.x
      Code:
        S3Bucket: devak-lambda-deployment-buckets # Ensure this is the correct bucket name
        S3Key: search-photos.zip