AWSTemplateFormatVersion: "2010-09-09"
Description: Frontend Infrastructure Stack for Photo Manager Application

Parameters:
  LambdaDeploymentBucket:
    Type: String
    Description: S3 bucket for storing Lambda deployment packages

Resources:
  FrontendBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "New-photo-manager-frontend-bucket"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  FrontendBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !GetAtt FrontendCloudFront.DomainName

  FrontendBucketOAI:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for frontend bucket"

  FrontendCloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: "FrontendBucketOrigin"
            DomainName: !GetAtt FrontendBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${FrontendBucketOAI}"
        DefaultCacheBehavior:
          TargetOriginId: "FrontendBucketOrigin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods:
            - "GET"
            - "HEAD"
            - "OPTIONS"
          CachedMethods:
            - "GET"
            - "HEAD"
          ForwardedValues:
            QueryString: true
          Compress: true
        Enabled: true
        DefaultRootObject: "index.html"
        PriceClass: "PriceClass_100"

Outputs:
  CloudFrontURL:
    Description: "URL for the CloudFront Distribution"
    Value: !GetAtt FrontendCloudFront.DomainName
  BucketName:
    Description: "Name of the S3 bucket for the frontend"
    Value: !Ref FrontendBucket
